#LIST METHODS

#APPEND
#THIS METHOD WILL ADD AN ITEM IN THE LIST AT THE END.

l=[10,20,30]
l.append("SOURADEEP")
print(l)

#INSERT METHOD
#THIS METHOD ADDS AN ITEM IN THE INSERT AT THE POSITION WE WANT TO INSERT

l.insert(0,"START")
print(l)

l.insert(-1,"END") #INSERT METHOD PUSHES THE PREVIOUS VALUE PRESENT ON THE INSERTED VALUE TO THE NEXT.
print(l)

l.insert(4,20)
print(l)

#COUNT METHOD
#COUNTS ANY PARTICULAR ITEM IN THE LIST

print('THE COUNT OF 20',l.count(20))
print('THE COUNT OF "SOURADEEP"',l.count("SOURADEEP"))

#REVERSING THE LIST
l.reverse()
print(l)

#DELETING ITEMS FROM THE ITEMS IN THE LIST
# 1.DELETE METHODS
# TAKES THE ITEM POSITION TO DELETE THE ITEM

del l[-1]    # DELETING THE LAST ITEM FROM THE LIST.
print(l)


# 2.REMOVE METHOD
#TAKES THE ITEM WHICH NEEDS TO BE REMOVED

l.remove("END")
print(l)


# 3.POP METHOD
#DELETING THE LAST ITEM FROM THE LIST
l.pop()
print(l)
