#OBJECTS AND REFERENCES

str1='SOURADEEP'
str2='SOURADEEP'
print(str1 is str2)  #  BOTH THE STRINGS ARE EQUAL AND EQUIVALENT.

LIST1=[10,20,30,40,50]
LIST2=[10,20,30,40,50]

print(LIST1 is LIST2)  # THIS CHECKS WHETHER 'LIST1' AND 'LIST2' ARE EXACTLY THE SAME OBJECT OR NOT.
print(LIST1 == LIST2) # BOTH ARE EQUIVALENT TO EACH OTHER.


#CHECKING BOTH THE IDS TO SEE THAT THEY ARE NOT SAME
print(id(LIST1))
print(id(LIST2))


#CHECKING THE IDS OF THE STRINGS TO VERIFY WHETHER THEY ARE SAME OR NOT.
print(id(str1))
print(id(str2))
